### ISSUE TITLE
how does the option hook declare a default value for an extra option?

### ISSUE THREAD

**Issue by joachim-n** [consolidation/annotated-command#110]
I'm going by this example in Drush:

```
  /**
   * When a hook extends a command with additional options, it must
   * implement declare those option(s) in a @hook option like this one.  Doing so will add
   * the option to the help text for the modified command, and will also
   * allow the new option to be specified on the command line.  Without
   * this, Drush will fail with an error when a user attempts to use
   * an unknown option.
   *
   * @hook option sql-sync
   * @option http-sync Copy the database via http instead of rsync.  Value is the url that the existing database dump can be found at.
   * @option http-sync-user Username for the protected directory containing the sql dump.
   * @option http-sync-password Password for the same directory.
   */
  public function optionsetSqlSync() {}
```

There doesn't seem to be a way for a default value for the extra option to be defined.

Having it set in the $options parameter for the command being enhanced causes a crash.

I think it would make sense to have an $options parameter in the hook function declaration.

**Comment by joachim-n** [comment]
Ah, this *is* possible:

```

  /**
   * Add the 'location' option to our commands.
   *
   * @hook option @code_builder
   * @option location Directory in which to store data. Use a relative path to
   *    store within public://, an absolute path otherwise. Defaults to
   *    public://code-builder.
   */
  public function optionLocation($options = ['location' => 'code-builder']) {}
```

Does need documenting though.

**Comment by greg-1-anderson** [comment]
The above uses of @hook option are not very good examples of how to add options to a command. A better example is the [alterFormatters](https://github.com/consolidation/annotated-command/blob/2.4.13/tests/src/alpha/AlphaCommandFile.php#L146) method in the tests. In this example, the `--french` option is tested in an alter hook, so an `@option french` annotation is added to declare the option. This annotation is picked up by the option validation code and also in help.

I am not a fan of empty methods that exist only to provide annotations. The point of annotations is to put them next to the code they modify. This library does not provide a good way to define common option sets that are used by a number of commands. In a way, it would be better to just duplicate the options, so that they are more visible when reading the primary command implementation. Or perhaps a named `@optionset` label might be added to pull in a definition. I'm not sure. The Drush example is using `@hook option` in place of this missing functionality, but `@hook option` was designed to add dynamic options in code. An example of the intended use for `@hook option` is the [additionalOptionForExampleTable](https://github.com/consolidation/annotated-command/blob/2.4.13/tests/src/alpha/AlphaCommandFile.php#L129) from the tests.

In any event, I will bolster the documentation a bit.

**Comment by joachim-n** [comment]
That PR hasn't added anything about how to define a default value for an option added by the option hook, AFAICT.

**Comment by greg-1-anderson** [comment]
Pushed another commit that adds this information; see @default in hook alter.
