### ISSUE TITLE
command discovery produces the wrong namespace

### ISSUE THREAD

**Issue by joachim-n** [consolidation/annotated-command#155]
### Steps to reproduce

I set up a composer package to provide a Drush command in this way, as explained in the Drush docs:

```
Nested (e.g. Commandfile is part of a Composer package)

    Filename: $PROJECT_ROOT/drush/Commands/dev_modules/ExampleCommands.php
    Namespace: Drush\Commands\dev_modules
```

### Expected behavior

The command file is picked up.

### Actual behavior

The command file is not picked up.

The array of file data returned by discovery has this:

```
  "/Users/joachim/Sites/_sandbox/drupal-code-builder-drush-9x/CodeBuilderDevCommands.php" => "\Drush\CodeBuilderDevCommands"
```

The class name that is in the array value is incorrect -- it should be: ```Drush\Commands\code_builder_commands\CodeBuilderDevCommands```

The reason for that is that discoverCommandFilesInLocation() makes assumptions about the namespace based on the filepath:

```
            $relativePathName = $file->getRelativePathname();
            $relativeNamespaceAndClassname = str_replace(
                ['/', '.php'],
                ['\\', ''],
                $relativePathName
            );
```

**Comment by joachim-n** [comment]
> Yep, as designed. The idea is that your namespace must conform to what the discovery class thinks it should be.

If this is by design, then fair enough.
But then why is Drush's documentation saying this is possible?

**Comment by greg-1-anderson** [comment]
Drush 9.0.0 shipped with a bug in global command namespace discovery. We made an adjustment a while back (9.3.0) to attempt to rectify the situation, but it seems it's still not quite right.

**Comment by greg-1-anderson** [comment]
This report confused me, because the reported path (`/Users/joachim/Sites/_sandbox/drupal-code-builder-drush-9x/CodeBuilderDevCommands.php`) does not include `drush/Commands`. In my testing, the path comes out as:
```
  '/Users/ganderson/local/drupal/drush9/drush/sut/drush/Commands/custom/example-site-wide-command/SutCommands.php' => '\\Drush\\Commands\\custom\\example-site-wide-command\\SutCommands',
```
I thought that the ask here was to make the namespace of the commandfile be independent from the path to the file. We can't really do that. What we **can** do, however, is transliterate from dashes to underscores, e.g. from `example-site-wide-command` to `example_site_wide_command`, as suggested at https://github.com/drush-ops/drush/pull/3615#issuecomment-420304021. Note that if you look at any module in Drupal core, e.g. `datetime_range`, `entity_reference`, etc., they already use underscores in the path instead of dashes so that there is alignment between the path name and the namespace.

It would also be super-helpful if the `custom` / `contrib` directory did not get included in the namespace. Taking specific things out of the path under the direction of the client (i.e. via a new API) might be a viable strategy.

I made a PR #156 to try this strategy. I will make a corresponding change to the Drush PR https://github.com/drush-ops/drush/pull/3687 to use that PR.
