### ISSUE TITLE
Recurse @hook 

### ISSUE THREAD

**Issue by ScreamingDev** [consolidation/annotated-command#205]
### Steps to reproduce

```
/**
     * @hook command bar
     */
    public function foo()
    {
        $this->writeln('foo');
    }

    /**
     * @hook command baz
     */
    public function bar()
    {
        $this->writeln('bar');
    }

    public function baz()
    {
        $this->writeln('baz');
    }
```

### Expected behavior

`robo baz` should output

> foo
> bar
> baz

And go even further so that Robo could build a big tree of tasks.
In general this task-hook-system could become a bit more detailled.
For example: I have several things to do before the build but they need to be in some semi-specific order (like `@hook pre-command build 0` for priority).

**But this issue is about recursing all the way to each hook
or finding an alternative way/word for doing so**

### Actual behavior
Tell us what happens instead

> baz
> bar

**Comment by greg-1-anderson** [comment]
`@hook command` is a special case, as the order it should be called is ambiguous. (Robo does not support hook ordering at the moment.). Try `pre-command`, and also, put your different hooks in different command files. If you have different hooks for the same function in the same file, you can just call them procedurally.

I'm not sure what your use-case is, but perhaps what you want are tasks instead of hooks. If your command returns a task collection, Robo will run it. You can alter the task collection with hooks before it is run, too. This isn't used much, and might need some enhancement to meet your needs. I've been thinking about how to rework it for a while, but haven't had a project to design and implement it for yet.

**Comment by ScreamingDev** [comment]
I tried "pre-command" which has the same issue. Because right now Robo supports 3 steps:

1. pre
2. command
3. post

But as soon as I need to assert the order of ...

1. download
2. install
3. actually do stuff
4. test the result
5. clean up

... the current hooks may mix up such order.

>  If you have different hooks for the same function in the same file, you can just call them procedurally.
> I'm not sure what your use-case is

Thing is I have different Traits for different situations:

* SCSS compiling (when there is some then a `use ScssTrait;` will be added)
* Image sprites
* Grunt
* ...

So per project I want to enable them with a simple `use ScssTrait` or other.
But I also have different commands:

```
public test() {}
public build() {}
public clean() {}
public assets() {}
```

So I don't want to change the functions everytime but rather just use a trait that knows what to do:

```php
trait ScssTrait {
 /**
  * @pre-command build
  * @command assets
  */
 function buildScss() { /* ... */ }
}
```

So my class `RoboFile` just gives an command-line interface of possible functions ("build", "assets" etc) and the traits hook into those. This way I can heavily reuse everything fitting to the project. This is a more "event-driven" approach which custom Tasks can not offer.

**Comment by greg-1-anderson** [comment]
OK it sounds like you're trying to use command hooks like AOP. They weren't really designed for that.

I'm not saying that your request is impossible, but perhaps it is a bit complex. I might consider a PR, but I'm not feeling inclined to support this in Robo at the moment.

**Comment by greg-1-anderson** [comment]
Maybe you should consider https://github.com/goaop/framework for your application instead.

**Comment by ScreamingDev** [comment]
But I love Robo :(
