### ISSUE TITLE
Default option values not being properly set

### ISSUE THREAD

**Issue by nerdstein** [consolidation/annotated-command#95]
### Steps to reproduce

I created a command class with the following function:

`public function initialize($options = ['project-dir' => __DIR__, 'gitignore' => TRUE]) {`

I ran `app category:initialize` to run the command.

### Expected behavior
The `$options['gitignore']` would be set to `TRUE`

### Actual behavior
The `$options['gitignore']` was set to `FALSE`

### System Configuration
php 5.5.38, MacOS Sierra

**Comment by greg-1-anderson** [comment]
`'gitignore' => false` indicates that `gitignore` is a binary option whose value is false if not provided, and true if it is provided.

Based on this definition, it is ambiguous what a default value of `true` should mean. When would this value be passed in as `false`?  Potentially, we could automatically define a `--no-gitignore` option that could be used for force a binary option to `false` if its default value is `true`.

Workaround: simply define `no-gitignore` => false.

Potentially, we could reject the entire command definition when the default value of an option is `true`, since this is not currently supported.

**Comment by nerdstein** [comment]
This is true and the work around is in place. It still may be worth exploring if variables are being set properly or to have some documentation on binary options

**Comment by greg-1-anderson** [comment]
In my experiment, I found that defining `'gitignore' => TRUE` always set the value of `$options['gitignore']` to `TRUE`, regardless of whether or not `--gitignore` appeared on the commandline or not.

Since the time this issue was originally posted, I modified the annotated-command library to restrict itself to Symfony Console 3.2.4, to avoid a bug introduced in version 3.2.5. I don't know if this may have some effect on how option values are handled in Robo. Run `composer update` and you will be rolled back to the older version of Symfony.

I [updated the documentation for this project](https://github.com/consolidation/annotated-command#option-default-values) to more clearly describe the valid values supported for command line options. I also updated the Robo "Getting Started" document to contain the same information; this later update will be published the next time a Robo release is tagged.

It's not clear what the correct behavior for a default value of `true` should be, so this issue will be resolved in documentation only for now.
